# Generated by Django 4.2.6 on 2023-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('participant_disability', models.CharField(choices=[('DA', 'Deficiência Auditiva'), ('DF', 'Deficiência Física'), ('DI', 'Deficiência Intelectual'), ('DV', 'Deficiência Visual'), ('TEA', 'Transtorno Espectro Autista')], max_length=3)),
                ('clinical_diagnosis', models.TextField()),
                ('functional_profile', models.TextField()),
                ('participation_modalities', models.TextField()),
                ('participation_observations', models.TextField()),
                ('attendance_frequency', models.IntegerField()),
                ('attended_dates', models.CharField(max_length=255)),
                ('absences_count', models.IntegerField()),
                ('absent_dates', models.CharField(blank=True, max_length=255)),
                ('school_name', models.CharField(max_length=255)),
                ('additional_observations', models.TextField()),
                ('dropout_list', models.TextField(blank=True)),
                ('dropout_reason', models.TextField(blank=True)),
                ('responding_teacher_name', models.CharField(max_length=255)),
            ],
        ),
    ]
