# Generated by Django 4.2.6 on 2023-11-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleformsintegration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='participantresponse',
            name='participant_disability',
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='participant_disability',
            field=models.ManyToManyField(to='googleformsintegration.disability'),
        ),
    ]
