# Generated by Django 4.2.6 on 2023-11-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleformsintegration', '0002_disability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantresponse',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino')], max_length=6),
        ),
        migrations.RemoveField(
            model_name='participantresponse',
            name='participant_disability',
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='participant_disability',
            field=models.CharField(choices=[('AUD', 'Deficiência Auditiva'), ('FIS', 'Deficiência Física'), ('INT', 'Deficiência Intelectual'), ('VIS', 'Deficiência Visual'), ('AUT', 'Transtorno Espectro Autista')], default=[''], max_length=3),
        ),
    ]
