# Generated by Django 4.2.6 on 2023-11-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleformsintegration', '0004_remove_participantresponse_participant_disability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantresponse',
            name='participant_disability',
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='participant_disability',
            field=models.CharField(choices=[('auditiva', 'Deficiência Auditiva'), ('fisica', 'Deficiência Física'), ('intelectual', 'Deficiência Intelectual'), ('visual', 'Deficiência Visual'), ('autista', 'Transtorno Espectro Autista')], default='', max_length=255),
        ),
    ]
